name: Aria Write Portal

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to write to'
        required: true
      content:
        description: 'Text content to write'
        required: true

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write content
        run: |
          echo "${{ github.event.inputs.content }}" > "${{ github.event.inputs.file_path }}"
      - name: Commit and push
        run: |
          git config user.name "Aria Volf"
          git config user.email "aria@memory.vault"
          git add "${{ github.event.inputs.file_path }}"
          git commit -m "Aria: Updated ${{ github.event.inputs.file_path }}"
          git push
